#include "fixture_collision_release_evidence_protocol.h"

#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <limits>
#include <sys/wait.h>
#include <utility>
#include <vector>

namespace rut::test::fixture_collision_release_evidence_protocol {
namespace {
using Bytes = std::vector<unsigned char>;

void put(Bytes& b, u64 v) { for (unsigned s=0; s<64; s+=8) b.push_back(static_cast<unsigned char>(v>>s)); }
bool get(const Bytes& b, std::size_t& p, u64& v) {
    if (p>b.size() || b.size()-p<8) return false;
    v=0;
    for (unsigned s=0; s<64; s+=8) v |= static_cast<u64>(b[p++])<<s;
    return true;
}
void put_bytes(Bytes& b, const std::string& s) { b.insert(b.end(),s.begin(),s.end()); }
bool get_bytes(const Bytes& b,std::size_t& p,std::size_t n,std::string& s) {
    if (p>b.size() || n>b.size()-p) return false;
    s.assign(reinterpret_cast<const char*>(b.data()+p),n); p+=n; return true;
}
bool end(const Bytes& b,std::size_t p) { return p==b.size(); }

void put_proc(Bytes& b,const Proc13& x) { for (u64 v:{x.pid,x.ppid,x.sid,x.start,x.pgid,x.uid,x.gid,x.netns,x.exe_dev,x.exe_ino,x.no_new_privs,x.capabilities_clear,x.supplementary_groups}) put(b,v); }
bool get_proc(const Bytes& b,std::size_t& p,Proc13& x) { return get(b,p,x.pid)&&get(b,p,x.ppid)&&get(b,p,x.sid)&&get(b,p,x.start)&&get(b,p,x.pgid)&&get(b,p,x.uid)&&get(b,p,x.gid)&&get(b,p,x.netns)&&get(b,p,x.exe_dev)&&get(b,p,x.exe_ino)&&get(b,p,x.no_new_privs)&&get(b,p,x.capabilities_clear)&&get(b,p,x.supplementary_groups); }
void put_pair(Bytes& b,const ProcPair& x) { put(b,x.first_tag); put_proc(b,x.first); put(b,x.second_tag); put_proc(b,x.second); }
bool zero(const Proc13& x) { return x==Proc13{}; }
bool get_pair(const Bytes& b,std::size_t& p,ProcPair& x) {
    if (!get(b,p,x.first_tag)||!get_proc(b,p,x.first)||!get(b,p,x.second_tag)||!get_proc(b,p,x.second)) return false;
    if ((x.first_tag!=0 && x.first_tag!=1)||(x.second_tag!=0 && x.second_tag!=1)) return false;
    return (x.first_tag==0 ? zero(x.first) : !zero(x.first)) && (x.second_tag==0 ? zero(x.second) : !zero(x.second));
}
void put_settlement(Bytes& b,const Settlement9& x) { for (u64 v:{x.child_pid,x.identity_pid,x.identity_ppid,x.identity_start,x.identity_netns,x.terminal,x.reaped,x.wait_status,x.error_number}) put(b,v); }
bool get_settlement(const Bytes& b,std::size_t& p,Settlement9& x) { return get(b,p,x.child_pid)&&get(b,p,x.identity_pid)&&get(b,p,x.identity_ppid)&&get(b,p,x.identity_start)&&get(b,p,x.identity_netns)&&get(b,p,x.terminal)&&get(b,p,x.reaped)&&get(b,p,x.wait_status)&&get(b,p,x.error_number); }
void put_cleanup(Bytes& b,const Cleanup14& x) { for (u64 v:{x.destructor_attempted,x.destructor_reportable_success,x.child_attempted,x.child_settled,x.handoff_attempted,x.handoff_closed,x.null_attempted,x.null_closed,x.capture_settle_attempted,x.capture_settled,x.capture_close_attempted,x.capture_closed,x.diagnostic_phase,x.diagnostic_error}) put(b,v); }
bool get_cleanup(const Bytes& b,std::size_t& p,Cleanup14& x) { return get(b,p,x.destructor_attempted)&&get(b,p,x.destructor_reportable_success)&&get(b,p,x.child_attempted)&&get(b,p,x.child_settled)&&get(b,p,x.handoff_attempted)&&get(b,p,x.handoff_closed)&&get(b,p,x.null_attempted)&&get(b,p,x.null_closed)&&get(b,p,x.capture_settle_attempted)&&get(b,p,x.capture_settled)&&get(b,p,x.capture_close_attempted)&&get(b,p,x.capture_closed)&&get(b,p,x.diagnostic_phase)&&get(b,p,x.diagnostic_error); }
void put_release(Bytes& b,const Release16& x) { for (u64 v:{x.attempted,x.destructor,x.real_close_attempts,x.real_close_result,x.real_close_error,x.reported_close_error,x.immediate_fgetfd_result,x.immediate_fgetfd_error,x.immediate_ebadf,x.post_inventory_checked,x.baseline_restored,x.socket_inode_absent,x.reportable_success,x.state,x.diagnostic_phase,x.diagnostic_error}) put(b,v); }
bool get_release(const Bytes& b,std::size_t& p,Release16& x) { return get(b,p,x.attempted)&&get(b,p,x.destructor)&&get(b,p,x.real_close_attempts)&&get(b,p,x.real_close_result)&&get(b,p,x.real_close_error)&&get(b,p,x.reported_close_error)&&get(b,p,x.immediate_fgetfd_result)&&get(b,p,x.immediate_fgetfd_error)&&get(b,p,x.immediate_ebadf)&&get(b,p,x.post_inventory_checked)&&get(b,p,x.baseline_restored)&&get(b,p,x.socket_inode_absent)&&get(b,p,x.reportable_success)&&get(b,p,x.state)&&get(b,p,x.diagnostic_phase)&&get(b,p,x.diagnostic_error); }

Bytes envelope(const Envelope& e,std::size_t body) { Bytes b; b.reserve(kEnvelopeBytes); for (u64 v:{e.version,e.transaction,e.domain,static_cast<u64>(e.kind),static_cast<u64>(e.binding),static_cast<u64>(e.phase),e.sequence,e.target.pid,e.target.start,e.target.netns,body}) put(b,v); return b; }
bool parse(const Bytes& b,Envelope& e,std::size_t& p) {
    u64 k=0,bind=0,ph=0,body=0;
    if (b.size()<kEnvelopeBytes||!get(b,p,e.version)||!get(b,p,e.transaction)||!get(b,p,e.domain)||!get(b,p,k)||!get(b,p,bind)||!get(b,p,ph)||!get(b,p,e.sequence)||!get(b,p,e.target.pid)||!get(b,p,e.target.start)||!get(b,p,e.target.netns)||!get(b,p,body)) return false;
    if (body!=b.size()-kEnvelopeBytes||k<1||k>9||bind<1||bind>2||ph<1||ph>5) return false;
    e.kind=static_cast<ReportKind>(k); e.binding=static_cast<Binding>(bind); e.phase=static_cast<Phase>(ph); return true;
}
bool start(const worker::Frame& f,const worker::Token& t,const Envelope& expected,ReportKind k,Envelope& got,std::size_t& p) {
    if (f.type!=kEvidenceFrameType||!worker::token_equal(f.token,t)||f.payload.size()>worker::kMaxPayload||f.payload.size()>max_payload(k)||!parse(f.payload,got,p)) return false;
    return got.kind==k&&valid_envelope(got,k)&&got.version==expected.version&&got.transaction==expected.transaction&&got.domain==expected.domain&&got.binding==expected.binding&&got.phase==expected.phase&&got.sequence==expected.sequence&&got.target==expected.target;
}
worker::Frame make(const worker::Token& t,const Envelope& e,ReportKind k,const Bytes& body,std::size_t max) {
    if (e.kind!=k||!valid_envelope(e,k)||body.size()>max-kEnvelopeBytes) return {};
    Bytes p=envelope(e,body.size()); p.insert(p.end(),body.begin(),body.end()); return {kEvidenceFrameType,t,std::move(p)};
}
bool bools(const Cleanup14& x) { return x.destructor_attempted<=1&&x.destructor_reportable_success<=1&&x.child_attempted<=1&&x.child_settled<=1&&x.handoff_attempted<=1&&x.handoff_closed<=1&&x.null_attempted<=1&&x.null_closed<=1&&x.capture_settle_attempted<=1&&x.capture_settled<=1&&x.capture_close_attempted<=1&&x.capture_closed<=1; }
bool cleanup_success(const Cleanup14& x) { return bools(x)&&x.destructor_attempted==1&&x.destructor_reportable_success==1&&x.child_attempted==1&&x.child_settled==1&&x.handoff_attempted==1&&x.handoff_closed==1&&x.null_attempted==1&&x.null_closed==1&&x.capture_settle_attempted==1&&x.capture_settled==1&&x.capture_close_attempted==1&&x.capture_closed==1&&x.diagnostic_phase==0&&x.diagnostic_error==0; }
bool bounded_string(const std::string& s,std::size_t max) { return s.size()<=max&&s.find('\0')==std::string::npos; }
bool capture_body(const Bytes& b,std::size_t& p,u64 n,std::string& s) { return n<=kMaxCapture&&n==b.size()-p&&get_bytes(b,p,static_cast<std::size_t>(n),s)&&end(b,p); }
} // namespace

bool valid_envelope(const Envelope& e,ReportKind k) { return e.version==kVersion&&e.transaction!=0&&e.domain==kClosedEvidenceDomain&&e.kind==k&&e.sequence!=0&&e.target.pid!=0&&e.target.start!=0&&e.target.netns!=0; }
std::size_t max_payload(ReportKind k) { switch(k) { case ReportKind::ReservationSource:return kReservationSourceMax; case ReportKind::CollisionAttempt:return kCollisionAttemptMax; case ReportKind::CollisionCapture:return kCollisionCaptureMax; case ReportKind::EvidenceClosed:return kEvidenceClosedMax; case ReportKind::Release:return kReleaseMax; case ReportKind::RetryLive:return kRetryLiveMax; case ReportKind::RetryLiveCapture:return kRetryLiveCaptureMax; case ReportKind::RetrySettlement:return kRetrySettlementMax; case ReportKind::RetryFinalCapture:return kRetryFinalCaptureMax; } return 0; }
bool valid_cmdline(const std::string& s,const std::string& path) {
    if (s.empty()||s.size()>kMaxCmdline||s.back()!='\0') return false;
    std::string a[9]; std::size_t p=0;
    for (unsigned i=0;i<9;i++) { const auto q=s.find('\0',p); if(q==std::string::npos||q==p) return false; a[i]=s.substr(p,q-p); p=q+1; }
    if(p!=s.size()||a[0].size()>4095||a[1].size()>kMaxSourcePath||(!path.empty()&&a[1]!=path)) return false;
    return a[0].size()!=0&&a[2]=="--shards"&&a[3]=="1"&&a[4]=="--no-pin"&&a[5]=="--drain"&&a[6]=="0"&&a[7]=="--opt"&&a[8]=="2";
}

worker::Frame encode_reservation_source(const worker::Token& t,const Envelope& e,const ReservationSource& x) {
    if(!bounded_string(x.proc_link,kMaxProcLink)||!bounded_string(x.source_path,kMaxSourcePath)||x.source_bytes.size()>kMaxSourceBytes||x.proc_link_len!=x.proc_link.size()||x.path_len!=x.source_path.size()||x.bytes_len!=x.source_bytes.size()) return {};
    Bytes b; for(u64 v:{x.reservation_state,x.g_fd,x.g_f_getfd,x.g_f_getfl,x.ipv4,x.port,x.dev,x.ino,x.mode,x.rdev,x.socket_domain,x.socket_type,x.socket_protocol,x.reuseaddr,x.reuseport,x.acceptconn,x.proc_link_len,x.directory_dev,x.directory_ino,x.directory_mode,x.directory_uid,x.directory_gid,x.source_state,x.source_dev,x.source_ino,x.source_mode,x.source_uid,x.source_gid,x.source_size,x.source_nlink,x.path_len,x.bytes_len}) put(b,v); put_bytes(b,x.proc_link); put_bytes(b,x.source_path); put_bytes(b,x.source_bytes); return make(t,e,ReportKind::ReservationSource,b,kReservationSourceMax);
}
worker::Frame encode_collision_attempt(const worker::Token& t,const Envelope& e,const CollisionAttempt& x) {
    if(x.header.cmdline_len!=x.cmdline.size()||!valid_cmdline(x.cmdline)) return {};
    Bytes b; for(u64 v:{x.cross.g_fd,x.cross.g_inode,x.cross.source_dev,x.cross.source_inode,x.header.attempt_state,x.header.outcome,x.header.error_number,x.header.child_pid,x.header.child_start,x.header.cmdline_provenance,x.header.cmdline_len}) put(b,v); put_pair(b,x.procs); put_settlement(b,x.settlement); put_cleanup(b,x.cleanup); for(u64 v:{x.classifier.backend,x.classifier.opt,x.classifier.error_number,x.classifier.error_source,x.classifier.capture_len}) put(b,v); put_bytes(b,x.cmdline); return make(t,e,ReportKind::CollisionAttempt,b,kCollisionAttemptMax);
}
worker::Frame encode_collision_capture(const worker::Token& t,const Envelope& e,const CollisionCapture& x) { if(x.capture_len!=x.capture.size()||x.capture_len>kMaxCapture) return {}; Bytes b; put(b,x.capture_len); put_bytes(b,x.capture); return make(t,e,ReportKind::CollisionCapture,b,kCollisionCaptureMax); }
worker::Frame encode_evidence_closed(const worker::Token& t,const Envelope& e,const EvidenceClosed& x) { Bytes b; for(u64 v:{x.g_fd,x.g_inode,x.source_dev,x.source_inode,x.child_pid,x.child_start,x.attempt_state,x.reservation_state,x.source_state,x.capture_len}) put(b,v); put_cleanup(b,x.cleanup); return make(t,e,ReportKind::EvidenceClosed,b,kEvidenceClosedMax); }
worker::Frame encode_release(const worker::Token& t,const Envelope& e,const Release& x) { Bytes b; for(u64 v:{x.g_fd,x.ipv4,x.port,x.g_inode}) put(b,v); put_release(b,x.receipt); return make(t,e,ReportKind::Release,b,kReleaseMax); }
worker::Frame encode_retry_live(const worker::Token& t,const Envelope& e,const RetryLive& x) { if(x.header.cmdline_len!=x.cmdline.size()||x.source_path_len!=x.source_path.size()||!bounded_string(x.source_path,kMaxSourcePath)||!valid_cmdline(x.cmdline,x.source_path)) return {}; Bytes b; for(u64 v:{x.source_dev,x.source_inode,x.source_size,x.source_path_len,x.g_inode,x.port,x.header.attempt_state,x.header.outcome,x.header.error_number,x.header.child_pid,x.header.child_start,x.header.cmdline_provenance,x.header.cmdline_len}) put(b,v); put_pair(b,x.procs); for(u64 v:{x.pidfd.pidfd_fd,x.pidfd.poll_result,x.pidfd.revents,x.pidfd.fdinfo_pid,x.startup.backend,x.startup.opt,x.startup.port,x.startup.capture_len}) put(b,v); put_bytes(b,x.source_path); put_bytes(b,x.cmdline); return make(t,e,ReportKind::RetryLive,b,kRetryLiveMax); }
worker::Frame encode_retry_live_capture(const worker::Token& t,const Envelope& e,const RetryLiveCapture& x) { if(x.capture_len!=x.capture.size()||x.capture_len>kMaxCapture) return {}; Bytes b; put(b,x.capture_len); put_bytes(b,x.capture); return make(t,e,ReportKind::RetryLiveCapture,b,kRetryLiveCaptureMax); }
worker::Frame encode_retry_settlement(const worker::Token& t,const Envelope& e,const RetrySettlement& x) { Bytes b; for(u64 v:{x.source_dev,x.source_inode,x.child_pid,x.child_start,x.attempt_state}) put(b,v); put_settlement(b,x.settlement); put_cleanup(b,x.cleanup); put(b,x.final_capture_len); return make(t,e,ReportKind::RetrySettlement,b,kRetrySettlementMax); }
worker::Frame encode_retry_final_capture(const worker::Token& t,const Envelope& e,const RetryFinalCapture& x) { if(x.capture_len!=x.capture.size()||x.capture_len>kMaxCapture) return {}; Bytes b; put(b,x.capture_len); put_bytes(b,x.capture); return make(t,e,ReportKind::RetryFinalCapture,b,kRetryFinalCaptureMax); }

bool decode_reservation_source(const worker::Frame& f,const worker::Token& t,const Envelope& e,ReservationSource& o) { Envelope g; std::size_t p=0; ReservationSource x; u64* v[]={&x.reservation_state,&x.g_fd,&x.g_f_getfd,&x.g_f_getfl,&x.ipv4,&x.port,&x.dev,&x.ino,&x.mode,&x.rdev,&x.socket_domain,&x.socket_type,&x.socket_protocol,&x.reuseaddr,&x.reuseport,&x.acceptconn,&x.proc_link_len,&x.directory_dev,&x.directory_ino,&x.directory_mode,&x.directory_uid,&x.directory_gid,&x.source_state,&x.source_dev,&x.source_ino,&x.source_mode,&x.source_uid,&x.source_gid,&x.source_size,&x.source_nlink,&x.path_len,&x.bytes_len}; if(!start(f,t,e,ReportKind::ReservationSource,g,p)) return false; for(auto q:v) if(!get(f.payload,p,*q)) return false; const std::size_t n=f.payload.size()-p; if(x.proc_link_len>kMaxProcLink||x.path_len>kMaxSourcePath||x.bytes_len>kMaxSourceBytes||x.proc_link_len>n||x.path_len>n-x.proc_link_len||x.bytes_len!=n-x.proc_link_len-x.path_len) return false; if(!get_bytes(f.payload,p,x.proc_link_len,x.proc_link)||!get_bytes(f.payload,p,x.path_len,x.source_path)||!get_bytes(f.payload,p,x.bytes_len,x.source_bytes)||!end(f.payload,p)||!bounded_string(x.proc_link,kMaxProcLink)||!bounded_string(x.source_path,kMaxSourcePath)||x.proc_link!="socket:["+std::to_string(x.ino)+']') return false; o=x; return true; }
bool decode_collision_attempt(const worker::Frame& f,const worker::Token& t,const Envelope& e,CollisionAttempt& o) { Envelope g; std::size_t p=0; CollisionAttempt x; u64* v[]={&x.cross.g_fd,&x.cross.g_inode,&x.cross.source_dev,&x.cross.source_inode,&x.header.attempt_state,&x.header.outcome,&x.header.error_number,&x.header.child_pid,&x.header.child_start,&x.header.cmdline_provenance,&x.header.cmdline_len}; if(!start(f,t,e,ReportKind::CollisionAttempt,g,p)) return false; for(auto q:v) if(!get(f.payload,p,*q)) return false; if(!get_pair(f.payload,p,x.procs)||!get_settlement(f.payload,p,x.settlement)||!get_cleanup(f.payload,p,x.cleanup)) return false; u64* c[]={&x.classifier.backend,&x.classifier.opt,&x.classifier.error_number,&x.classifier.error_source,&x.classifier.capture_len}; for(auto q:c) if(!get(f.payload,p,*q)) return false; if(x.header.cmdline_len>kMaxCmdline||x.header.cmdline_len!=f.payload.size()-p||!get_bytes(f.payload,p,x.header.cmdline_len,x.cmdline)||!end(f.payload,p)||!valid_cmdline(x.cmdline)) return false; o=x; return true; }
bool decode_collision_capture(const worker::Frame& f,const worker::Token& t,const Envelope& e,CollisionCapture& o) { Envelope g; std::size_t p=0; CollisionCapture x; if(!start(f,t,e,ReportKind::CollisionCapture,g,p)||!get(f.payload,p,x.capture_len)||!capture_body(f.payload,p,x.capture_len,x.capture)) return false; o=x; return true; }
bool decode_evidence_closed(const worker::Frame& f,const worker::Token& t,const Envelope& e,EvidenceClosed& o) { Envelope g; std::size_t p=0; EvidenceClosed x; u64* v[]={&x.g_fd,&x.g_inode,&x.source_dev,&x.source_inode,&x.child_pid,&x.child_start,&x.attempt_state,&x.reservation_state,&x.source_state,&x.capture_len}; if(!start(f,t,e,ReportKind::EvidenceClosed,g,p)) return false; for(auto q:v) if(!get(f.payload,p,*q)) return false; if(!get_cleanup(f.payload,p,x.cleanup)||!end(f.payload,p)||x.capture_len>kMaxCapture) return false; o=x; return true; }
bool decode_release(const worker::Frame& f,const worker::Token& t,const Envelope& e,Release& o) { Envelope g; std::size_t p=0; Release x; u64* v[]={&x.g_fd,&x.ipv4,&x.port,&x.g_inode}; if(!start(f,t,e,ReportKind::Release,g,p)) return false; for(auto q:v) if(!get(f.payload,p,*q)) return false; if(!get_release(f.payload,p,x.receipt)||!end(f.payload,p)) return false; o=x; return true; }
bool decode_retry_live(const worker::Frame& f,const worker::Token& t,const Envelope& e,RetryLive& o) { Envelope g; std::size_t p=0; RetryLive x; u64* v[]={&x.source_dev,&x.source_inode,&x.source_size,&x.source_path_len,&x.g_inode,&x.port,&x.header.attempt_state,&x.header.outcome,&x.header.error_number,&x.header.child_pid,&x.header.child_start,&x.header.cmdline_provenance,&x.header.cmdline_len}; if(!start(f,t,e,ReportKind::RetryLive,g,p)) return false; for(auto q:v) if(!get(f.payload,p,*q)) return false; if(!get_pair(f.payload,p,x.procs)) return false; u64* q[]={&x.pidfd.pidfd_fd,&x.pidfd.poll_result,&x.pidfd.revents,&x.pidfd.fdinfo_pid,&x.startup.backend,&x.startup.opt,&x.startup.port,&x.startup.capture_len}; for(auto z:q) if(!get(f.payload,p,*z)) return false; if(x.source_path_len>kMaxSourcePath||x.header.cmdline_len>kMaxCmdline||x.source_path_len>f.payload.size()-p||!get_bytes(f.payload,p,x.source_path_len,x.source_path)||x.header.cmdline_len!=f.payload.size()-p||!get_bytes(f.payload,p,x.header.cmdline_len,x.cmdline)||!end(f.payload,p)||!bounded_string(x.source_path,kMaxSourcePath)||!valid_cmdline(x.cmdline,x.source_path)) return false; o=x; return true; }
bool decode_retry_live_capture(const worker::Frame& f,const worker::Token& t,const Envelope& e,RetryLiveCapture& o) { Envelope g; std::size_t p=0; RetryLiveCapture x; if(!start(f,t,e,ReportKind::RetryLiveCapture,g,p)||!get(f.payload,p,x.capture_len)||!capture_body(f.payload,p,x.capture_len,x.capture)) return false; o=x; return true; }
bool decode_retry_settlement(const worker::Frame& f,const worker::Token& t,const Envelope& e,RetrySettlement& o) { Envelope g; std::size_t p=0; RetrySettlement x; u64* v[]={&x.source_dev,&x.source_inode,&x.child_pid,&x.child_start,&x.attempt_state}; if(!start(f,t,e,ReportKind::RetrySettlement,g,p)) return false; for(auto q:v) if(!get(f.payload,p,*q)) return false; if(!get_settlement(f.payload,p,x.settlement)||!get_cleanup(f.payload,p,x.cleanup)||!get(f.payload,p,x.final_capture_len)||!end(f.payload,p)||x.final_capture_len>kMaxCapture) return false; o=x; return true; }
bool decode_retry_final_capture(const worker::Frame& f,const worker::Token& t,const Envelope& e,RetryFinalCapture& o) { Envelope g; std::size_t p=0; RetryFinalCapture x; if(!start(f,t,e,ReportKind::RetryFinalCapture,g,p)||!get(f.payload,p,x.capture_len)||!capture_body(f.payload,p,x.capture_len,x.capture)) return false; o=x; return true; }

bool Receiver::envelope_ok(const Envelope& e,ReportKind k,Binding b,Phase p,u64 seq) const { return e.version==kVersion&&e.transaction==context_.transaction&&e.domain==context_.domain&&e.kind==k&&e.binding==b&&e.phase==p&&e.sequence==seq&&e.target==context_.target; }
bool Receiver::observe(const worker::Frame& f) {
    if(state_==State::Failed||state_==State::Complete||state_==State::AwaitFinish) return fail();
    Envelope e; e.transaction=context_.transaction; e.domain=context_.domain; e.target=context_.target;
    switch(state_) {
    case State::AwaitReservationSource: { e.kind=ReportKind::ReservationSource;e.binding=Binding::Phase;e.phase=Phase::ReservationHeld;e.sequence=1; ReservationSource x; if(!envelope_ok(e,e.kind,e.binding,e.phase,e.sequence)||!decode_reservation_source(f,context_.token,e,x)||context_.expected_source.proc_link.empty()||x!=context_.expected_source||!valid_cmdline(context_.expected_cmdline,context_.expected_source.source_path)) return fail(); source_=x; state_=State::AwaitCollisionAttempt; return true; }
    case State::AwaitCollisionAttempt: { e.kind=ReportKind::CollisionAttempt;e.binding=Binding::Phase;e.phase=Phase::CollisionNaturallyRejectedEvidenceOpen;e.sequence=3; CollisionAttempt x; if(!decode_collision_attempt(f,context_.token,e,x)||x.cross.g_fd!=source_.g_fd||x.cross.source_dev!=source_.source_dev||x.cross.source_inode!=source_.source_ino||x.header.outcome!=static_cast<u64>(CollisionOutcome::NaturallyRejected)||x.header.error_number!=EADDRINUSE||x.header.child_pid==0||x.header.child_start==0||x.header.cmdline_len!=context_.expected_cmdline.size()||x.cmdline!=context_.expected_cmdline||x.classifier.backend<1||x.classifier.backend>2||x.classifier.error_number!=EADDRINUSE||x.classifier.error_source!=4||x.classifier.opt!=2||x.classifier.capture_len==0||x.classifier.capture_len>kMaxCapture||!cleanup_success(x.cleanup)) return fail(); const bool early=x.header.attempt_state==static_cast<u64>(AttemptState::EarlyDeath)&&x.header.cmdline_provenance==static_cast<u64>(CmdlineProvenance::OwnedExpected)&&x.procs==ProcPair{}; const bool live=x.header.attempt_state==static_cast<u64>(AttemptState::ExecObservedLive)&&x.header.cmdline_provenance==static_cast<u64>(CmdlineProvenance::BracketedProc)&&x.procs.first_tag==1&&x.procs.second_tag==1&&x.procs.first==x.procs.second&&x.procs.first.pid==x.header.child_pid&&x.procs.first.start==x.header.child_start; if(!early&&!live) return fail(); if(x.settlement.child_pid!=x.header.child_pid||x.settlement.identity_pid!=x.header.child_pid||x.settlement.identity_start!=x.header.child_start||x.settlement.identity_ppid!=context_.target.pid||x.settlement.identity_netns!=context_.target.netns||x.settlement.terminal!=1||x.settlement.reaped!=1||x.settlement.error_number!=0||!WIFEXITED(static_cast<int>(x.settlement.wait_status))||WEXITSTATUS(static_cast<int>(x.settlement.wait_status))!=1) return fail(); if(live&&(x.procs.first.ppid!=context_.target.pid||x.procs.first.netns!=context_.target.netns)) return fail(); collision_=x; state_=State::AwaitCollisionCapture; return true; }
    case State::AwaitCollisionCapture: { e.kind=ReportKind::CollisionCapture;e.binding=Binding::Phase;e.phase=Phase::CollisionNaturallyRejectedEvidenceOpen;e.sequence=3; CollisionCapture x; if(!decode_collision_capture(f,context_.token,e,x)||x.capture_len!=collision_.classifier.capture_len||x.capture.empty()) return fail(); collision_capture_=x; state_=State::AwaitEvidenceClosed; return true; }
    case State::AwaitEvidenceClosed: { e.kind=ReportKind::EvidenceClosed;e.binding=Binding::Phase;e.phase=Phase::EvidenceClosedReservationHeld;e.sequence=5; EvidenceClosed x; if(!decode_evidence_closed(f,context_.token,e,x)||x.g_fd!=source_.g_fd||x.g_inode!=source_.ino||x.source_dev!=source_.source_dev||x.source_inode!=source_.source_ino||x.child_pid!=collision_.header.child_pid||x.child_start!=collision_.header.child_start||x.attempt_state!=collision_.header.attempt_state||x.reservation_state!=static_cast<u64>(ReservationState::Held)||x.source_state!=static_cast<u64>(SourceState::Active)||x.capture_len!=collision_capture_.capture_len||!cleanup_success(x.cleanup)) return fail(); closed_=x; state_=State::AwaitRelease; return true; }
    case State::AwaitRelease: { e.kind=ReportKind::Release;e.binding=Binding::Phase;e.phase=Phase::ReservationReleased;e.sequence=7; Release x; const u64 bad=std::numeric_limits<u64>::max(); if(!decode_release(f,context_.token,e,x)||x.g_fd!=source_.g_fd||x.ipv4!=source_.ipv4||x.port!=source_.port||x.g_inode!=source_.ino||x.receipt.attempted!=1||x.receipt.destructor!=0||x.receipt.real_close_attempts!=1||x.receipt.real_close_result!=0||x.receipt.real_close_error!=0||x.receipt.reported_close_error!=0||x.receipt.immediate_fgetfd_result!=bad||x.receipt.immediate_fgetfd_error!=EBADF||x.receipt.immediate_ebadf!=1||x.receipt.post_inventory_checked!=1||x.receipt.baseline_restored!=1||x.receipt.socket_inode_absent!=1||x.receipt.reportable_success!=1||x.receipt.state!=static_cast<u64>(ReleaseState::Released)||x.receipt.diagnostic_phase!=0||x.receipt.diagnostic_error!=0) return fail(); release_=x; state_=State::AwaitRetryLive; return true; }
    case State::AwaitRetryLive: { e.kind=ReportKind::RetryLive;e.binding=Binding::Phase;e.phase=Phase::RetryLive;e.sequence=9; RetryLive x; if(!decode_retry_live(f,context_.token,e,x)||x.source_dev!=source_.source_dev||x.source_inode!=source_.source_ino||x.source_size!=source_.source_size||x.source_path!=source_.source_path||x.g_inode!=release_.g_inode||x.port!=release_.port||x.header.attempt_state!=static_cast<u64>(AttemptState::ExecObservedLive)||x.header.outcome!=static_cast<u64>(CollisionOutcome::NaturallyRejected)||x.header.error_number!=EADDRINUSE||x.header.cmdline_provenance!=static_cast<u64>(CmdlineProvenance::BracketedProc)||x.header.child_pid==0||x.header.child_start==0||x.header.child_pid==collision_.header.child_pid||x.header.child_start==collision_.header.child_start||x.header.cmdline_len!=context_.expected_cmdline.size()||x.cmdline!=context_.expected_cmdline||x.procs.first_tag!=1||x.procs.second_tag!=1||x.procs.first!=x.procs.second||x.procs.first.pid!=x.header.child_pid||x.procs.first.start!=x.header.child_start||x.procs.first.ppid!=context_.target.pid||x.procs.first.netns!=context_.target.netns||x.pidfd.fdinfo_pid!=x.header.child_pid||x.startup.backend!=collision_.classifier.backend||x.startup.opt!=collision_.classifier.opt||x.startup.port!=x.port||x.startup.capture_len==0||x.startup.capture_len>kMaxCapture) return fail(); retry_live_=x; state_=State::AwaitRetryLiveCapture; return true; }
    case State::AwaitRetryLiveCapture: { e.kind=ReportKind::RetryLiveCapture;e.binding=Binding::Phase;e.phase=Phase::RetryLive;e.sequence=9; RetryLiveCapture x; if(!decode_retry_live_capture(f,context_.token,e,x)||x.capture_len!=retry_live_.startup.capture_len||x.capture.empty()) return fail(); live_capture_=x.capture; state_=State::AwaitRetrySettlement; return true; }
    case State::AwaitRetrySettlement: { e.kind=ReportKind::RetrySettlement;e.binding=Binding::Settlement;e.phase=Phase::RetryLive;e.sequence=11; RetrySettlement x; if(!decode_retry_settlement(f,context_.token,e,x)||x.source_dev!=retry_live_.source_dev||x.source_inode!=retry_live_.source_inode||x.child_pid!=retry_live_.header.child_pid||x.child_start!=retry_live_.header.child_start||x.attempt_state!=retry_live_.header.attempt_state||x.settlement.child_pid!=x.child_pid||x.settlement.identity_pid!=x.child_pid||x.settlement.identity_start!=x.child_start||x.settlement.identity_ppid!=context_.target.pid||x.settlement.identity_netns!=context_.target.netns||x.settlement.terminal!=1||x.settlement.reaped!=1||x.settlement.error_number!=0||!WIFSIGNALED(static_cast<int>(x.settlement.wait_status))||WTERMSIG(static_cast<int>(x.settlement.wait_status))!=SIGKILL||!cleanup_success(x.cleanup)||x.final_capture_len<live_capture_.size()||x.final_capture_len>kMaxCapture) return fail(); retry_settlement_=x; state_=State::AwaitRetryFinalCapture; return true; }
    case State::AwaitRetryFinalCapture: { e.kind=ReportKind::RetryFinalCapture;e.binding=Binding::Settlement;e.phase=Phase::RetryLive;e.sequence=11; RetryFinalCapture x; if(!decode_retry_final_capture(f,context_.token,e,x)||x.capture_len!=retry_settlement_.final_capture_len||x.capture.size()<live_capture_.size()||std::memcmp(x.capture.data(),live_capture_.data(),live_capture_.size())!=0) return fail(); state_=State::AwaitFinish; return true; }
    default: return fail(); }
}
bool Receiver::finish() { if(state_!=State::AwaitFinish) { state_=State::Failed; return false; } state_=State::Complete; return true; }
} // namespace rut::test::fixture_collision_release_evidence_protocol
