#pragma once

#include "rut/compiler/diagnostic.h"
#include "rut/nginx/parser.h"

namespace rut::nginx {

// The converter deliberately returns owned, bounded source text rather than a
// view into the nginx input. This keeps the generated program usable after the
// parsed nginx source is released and makes overflow a diagnostic rather than
// a truncated program.
struct RutSource {
    // The previously accepted models require at most 8749 payload bytes.
    // An exact local action emits its body once without escaping. Reserving
    // its growth from 64 to 4094 bytes therefore bounds every composition,
    // including maximum listener, upstream, timeout and exact-path values.
    // Keep one byte for the NUL; writer completion remains len < kCapacity.
    static constexpr u32 kCapacity = 8750u + (kMaxLocalReturnBodyLen - 64u);
    char data[kCapacity]{};
    u32 len = 0;

    [[nodiscard]] Str view() const { return {data, len}; }
};

// Owned output for the bounded request-length http profile. The accessLog
// declaration contributes at most 329 bytes (19-byte prefix, 255-byte path,
// 55-byte suffix), in addition to the bounded server source including its NUL.
struct HttpProfileRutSource {
    static constexpr u32 kMaxAccessLogDeclarationLen = 329u;
    static constexpr u32 kCapacity = RutSource::kCapacity + kMaxAccessLogDeclarationLen;
    char data[kCapacity]{};
    u32 len = 0;

    [[nodiscard]] Str view() const { return {data, len}; }
};

static_assert(HttpProfileRutSource::kMaxAccessLogDeclarationLen == 19u + 255u + 55u);
static_assert(HttpProfileRutSource::kCapacity ==
              RutSource::kCapacity + HttpProfileRutSource::kMaxAccessLogDeclarationLen);

// Lower only the parser's exact minimal semantic model to deterministic RUT
// source. The output is intentionally nginx-independent RUT policy syntax;
// unsupported/forged model values fail closed with the model's source span.
FrontendResult<RutSource> lower_to_rut(const Server& server);

// Lower the exact bounded http profile to an ordinary RUT accessLog declaration
// followed by the unchanged Server lowering. `profile.source` must remain
// readable and byte-stable until this call returns. The returned source owns
// every emitted byte and is independent of the nginx input afterward.
FrontendResult<HttpProfileRutSource> lower_to_rut(const HttpProfile& profile);

// Lower a complete nginx source envelope after reparsing and authenticating
// both its outer spans and the suffix-local HttpProfile model. `config.source`
// must remain readable and byte-stable until this call returns. The returned
// source owns all generated bytes and is independent of the nginx input.
FrontendResult<HttpProfileRutSource> lower_to_rut(const NginxHttpConfig& config);

}  // namespace rut::nginx
